// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/studentinfo.proto

package cs682.samples.protos;

public final class StudentInfo {
  private StudentInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string first_name = 1;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string first_name = 1;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string last_name = 2;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string last_name = 2;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>repeated double score = 3;</code>
     * @return A list containing the score.
     */
    java.util.List<java.lang.Double> getScoreList();
    /**
     * <code>repeated double score = 3;</code>
     * @return The count of score.
     */
    int getScoreCount();
    /**
     * <code>repeated double score = 3;</code>
     * @param index The index of the element to return.
     * @return The score at the given index.
     */
    double getScore(int index);

    /**
     * <code>.Phone phone = 4;</code>
     * @return Whether the phone field is set.
     */
    boolean hasPhone();
    /**
     * <code>.Phone phone = 4;</code>
     * @return The phone.
     */
    cs682.samples.protos.StudentInfo.Phone getPhone();
    /**
     * <code>.Phone phone = 4;</code>
     */
    cs682.samples.protos.StudentInfo.PhoneOrBuilder getPhoneOrBuilder();
  }
  /**
   * Protobuf type {@code Student}
   */
  public static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      firstName_ = "";
      lastName_ = "";
      score_ = emptyDoubleList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 25: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                score_ = newDoubleList();
                mutable_bitField0_ |= 0x00000001;
              }
              score_.addDouble(input.readDouble());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                score_ = newDoubleList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                score_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              cs682.samples.protos.StudentInfo.Phone.Builder subBuilder = null;
              if (phone_ != null) {
                subBuilder = phone_.toBuilder();
              }
              phone_ = input.readMessage(cs682.samples.protos.StudentInfo.Phone.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(phone_);
                phone_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          score_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cs682.samples.protos.StudentInfo.internal_static_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cs682.samples.protos.StudentInfo.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cs682.samples.protos.StudentInfo.Student.class, cs682.samples.protos.StudentInfo.Student.Builder.class);
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string first_name = 1;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string first_name = 1;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string last_name = 2;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string last_name = 2;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.DoubleList score_;
    /**
     * <code>repeated double score = 3;</code>
     * @return A list containing the score.
     */
    @java.lang.Override
    public java.util.List<java.lang.Double>
        getScoreList() {
      return score_;
    }
    /**
     * <code>repeated double score = 3;</code>
     * @return The count of score.
     */
    public int getScoreCount() {
      return score_.size();
    }
    /**
     * <code>repeated double score = 3;</code>
     * @param index The index of the element to return.
     * @return The score at the given index.
     */
    public double getScore(int index) {
      return score_.getDouble(index);
    }
    private int scoreMemoizedSerializedSize = -1;

    public static final int PHONE_FIELD_NUMBER = 4;
    private cs682.samples.protos.StudentInfo.Phone phone_;
    /**
     * <code>.Phone phone = 4;</code>
     * @return Whether the phone field is set.
     */
    @java.lang.Override
    public boolean hasPhone() {
      return phone_ != null;
    }
    /**
     * <code>.Phone phone = 4;</code>
     * @return The phone.
     */
    @java.lang.Override
    public cs682.samples.protos.StudentInfo.Phone getPhone() {
      return phone_ == null ? cs682.samples.protos.StudentInfo.Phone.getDefaultInstance() : phone_;
    }
    /**
     * <code>.Phone phone = 4;</code>
     */
    @java.lang.Override
    public cs682.samples.protos.StudentInfo.PhoneOrBuilder getPhoneOrBuilder() {
      return getPhone();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
      }
      if (getScoreList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(scoreMemoizedSerializedSize);
      }
      for (int i = 0; i < score_.size(); i++) {
        output.writeDoubleNoTag(score_.getDouble(i));
      }
      if (phone_ != null) {
        output.writeMessage(4, getPhone());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getScoreList().size();
        size += dataSize;
        if (!getScoreList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        scoreMemoizedSerializedSize = dataSize;
      }
      if (phone_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPhone());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cs682.samples.protos.StudentInfo.Student)) {
        return super.equals(obj);
      }
      cs682.samples.protos.StudentInfo.Student other = (cs682.samples.protos.StudentInfo.Student) obj;

      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getScoreList()
          .equals(other.getScoreList())) return false;
      if (hasPhone() != other.hasPhone()) return false;
      if (hasPhone()) {
        if (!getPhone()
            .equals(other.getPhone())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      if (getScoreCount() > 0) {
        hash = (37 * hash) + SCORE_FIELD_NUMBER;
        hash = (53 * hash) + getScoreList().hashCode();
      }
      if (hasPhone()) {
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + getPhone().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cs682.samples.protos.StudentInfo.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cs682.samples.protos.StudentInfo.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cs682.samples.protos.StudentInfo.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cs682.samples.protos.StudentInfo.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cs682.samples.protos.StudentInfo.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cs682.samples.protos.StudentInfo.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cs682.samples.protos.StudentInfo.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cs682.samples.protos.StudentInfo.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cs682.samples.protos.StudentInfo.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cs682.samples.protos.StudentInfo.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cs682.samples.protos.StudentInfo.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cs682.samples.protos.StudentInfo.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cs682.samples.protos.StudentInfo.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        cs682.samples.protos.StudentInfo.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cs682.samples.protos.StudentInfo.internal_static_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cs682.samples.protos.StudentInfo.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cs682.samples.protos.StudentInfo.Student.class, cs682.samples.protos.StudentInfo.Student.Builder.class);
      }

      // Construct using cs682.samples.protos.StudentInfo.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        firstName_ = "";

        lastName_ = "";

        score_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (phoneBuilder_ == null) {
          phone_ = null;
        } else {
          phone_ = null;
          phoneBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cs682.samples.protos.StudentInfo.internal_static_Student_descriptor;
      }

      @java.lang.Override
      public cs682.samples.protos.StudentInfo.Student getDefaultInstanceForType() {
        return cs682.samples.protos.StudentInfo.Student.getDefaultInstance();
      }

      @java.lang.Override
      public cs682.samples.protos.StudentInfo.Student build() {
        cs682.samples.protos.StudentInfo.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cs682.samples.protos.StudentInfo.Student buildPartial() {
        cs682.samples.protos.StudentInfo.Student result = new cs682.samples.protos.StudentInfo.Student(this);
        int from_bitField0_ = bitField0_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        if (((bitField0_ & 0x00000001) != 0)) {
          score_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.score_ = score_;
        if (phoneBuilder_ == null) {
          result.phone_ = phone_;
        } else {
          result.phone_ = phoneBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cs682.samples.protos.StudentInfo.Student) {
          return mergeFrom((cs682.samples.protos.StudentInfo.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cs682.samples.protos.StudentInfo.Student other) {
        if (other == cs682.samples.protos.StudentInfo.Student.getDefaultInstance()) return this;
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.score_.isEmpty()) {
          if (score_.isEmpty()) {
            score_ = other.score_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureScoreIsMutable();
            score_.addAll(other.score_);
          }
          onChanged();
        }
        if (other.hasPhone()) {
          mergePhone(other.getPhone());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cs682.samples.protos.StudentInfo.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cs682.samples.protos.StudentInfo.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object firstName_ = "";
      /**
       * <code>string first_name = 1;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string first_name = 1;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string first_name = 1;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 1;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string last_name = 2;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_name = 2;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_name = 2;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 2;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.DoubleList score_ = emptyDoubleList();
      private void ensureScoreIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          score_ = mutableCopy(score_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double score = 3;</code>
       * @return A list containing the score.
       */
      public java.util.List<java.lang.Double>
          getScoreList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(score_) : score_;
      }
      /**
       * <code>repeated double score = 3;</code>
       * @return The count of score.
       */
      public int getScoreCount() {
        return score_.size();
      }
      /**
       * <code>repeated double score = 3;</code>
       * @param index The index of the element to return.
       * @return The score at the given index.
       */
      public double getScore(int index) {
        return score_.getDouble(index);
      }
      /**
       * <code>repeated double score = 3;</code>
       * @param index The index to set the value at.
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(
          int index, double value) {
        ensureScoreIsMutable();
        score_.setDouble(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double score = 3;</code>
       * @param value The score to add.
       * @return This builder for chaining.
       */
      public Builder addScore(double value) {
        ensureScoreIsMutable();
        score_.addDouble(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double score = 3;</code>
       * @param values The score to add.
       * @return This builder for chaining.
       */
      public Builder addAllScore(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureScoreIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, score_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double score = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        score_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private cs682.samples.protos.StudentInfo.Phone phone_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cs682.samples.protos.StudentInfo.Phone, cs682.samples.protos.StudentInfo.Phone.Builder, cs682.samples.protos.StudentInfo.PhoneOrBuilder> phoneBuilder_;
      /**
       * <code>.Phone phone = 4;</code>
       * @return Whether the phone field is set.
       */
      public boolean hasPhone() {
        return phoneBuilder_ != null || phone_ != null;
      }
      /**
       * <code>.Phone phone = 4;</code>
       * @return The phone.
       */
      public cs682.samples.protos.StudentInfo.Phone getPhone() {
        if (phoneBuilder_ == null) {
          return phone_ == null ? cs682.samples.protos.StudentInfo.Phone.getDefaultInstance() : phone_;
        } else {
          return phoneBuilder_.getMessage();
        }
      }
      /**
       * <code>.Phone phone = 4;</code>
       */
      public Builder setPhone(cs682.samples.protos.StudentInfo.Phone value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          phone_ = value;
          onChanged();
        } else {
          phoneBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Phone phone = 4;</code>
       */
      public Builder setPhone(
          cs682.samples.protos.StudentInfo.Phone.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          phone_ = builderForValue.build();
          onChanged();
        } else {
          phoneBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Phone phone = 4;</code>
       */
      public Builder mergePhone(cs682.samples.protos.StudentInfo.Phone value) {
        if (phoneBuilder_ == null) {
          if (phone_ != null) {
            phone_ =
              cs682.samples.protos.StudentInfo.Phone.newBuilder(phone_).mergeFrom(value).buildPartial();
          } else {
            phone_ = value;
          }
          onChanged();
        } else {
          phoneBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Phone phone = 4;</code>
       */
      public Builder clearPhone() {
        if (phoneBuilder_ == null) {
          phone_ = null;
          onChanged();
        } else {
          phone_ = null;
          phoneBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Phone phone = 4;</code>
       */
      public cs682.samples.protos.StudentInfo.Phone.Builder getPhoneBuilder() {
        
        onChanged();
        return getPhoneFieldBuilder().getBuilder();
      }
      /**
       * <code>.Phone phone = 4;</code>
       */
      public cs682.samples.protos.StudentInfo.PhoneOrBuilder getPhoneOrBuilder() {
        if (phoneBuilder_ != null) {
          return phoneBuilder_.getMessageOrBuilder();
        } else {
          return phone_ == null ?
              cs682.samples.protos.StudentInfo.Phone.getDefaultInstance() : phone_;
        }
      }
      /**
       * <code>.Phone phone = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cs682.samples.protos.StudentInfo.Phone, cs682.samples.protos.StudentInfo.Phone.Builder, cs682.samples.protos.StudentInfo.PhoneOrBuilder> 
          getPhoneFieldBuilder() {
        if (phoneBuilder_ == null) {
          phoneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cs682.samples.protos.StudentInfo.Phone, cs682.samples.protos.StudentInfo.Phone.Builder, cs682.samples.protos.StudentInfo.PhoneOrBuilder>(
                  getPhone(),
                  getParentForChildren(),
                  isClean());
          phone_ = null;
        }
        return phoneBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final cs682.samples.protos.StudentInfo.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cs682.samples.protos.StudentInfo.Student();
    }

    public static cs682.samples.protos.StudentInfo.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cs682.samples.protos.StudentInfo.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Phone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 country_code = 1;</code>
     * @return The countryCode.
     */
    int getCountryCode();

    /**
     * <code>int32 area_code = 2;</code>
     * @return The areaCode.
     */
    int getAreaCode();

    /**
     * <code>int32 number = 3;</code>
     * @return The number.
     */
    int getNumber();
  }
  /**
   * Protobuf type {@code Phone}
   */
  public static final class Phone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Phone)
      PhoneOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Phone.newBuilder() to construct.
    private Phone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Phone() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Phone();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Phone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              countryCode_ = input.readInt32();
              break;
            }
            case 16: {

              areaCode_ = input.readInt32();
              break;
            }
            case 24: {

              number_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cs682.samples.protos.StudentInfo.internal_static_Phone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cs682.samples.protos.StudentInfo.internal_static_Phone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cs682.samples.protos.StudentInfo.Phone.class, cs682.samples.protos.StudentInfo.Phone.Builder.class);
    }

    public static final int COUNTRY_CODE_FIELD_NUMBER = 1;
    private int countryCode_;
    /**
     * <code>int32 country_code = 1;</code>
     * @return The countryCode.
     */
    @java.lang.Override
    public int getCountryCode() {
      return countryCode_;
    }

    public static final int AREA_CODE_FIELD_NUMBER = 2;
    private int areaCode_;
    /**
     * <code>int32 area_code = 2;</code>
     * @return The areaCode.
     */
    @java.lang.Override
    public int getAreaCode() {
      return areaCode_;
    }

    public static final int NUMBER_FIELD_NUMBER = 3;
    private int number_;
    /**
     * <code>int32 number = 3;</code>
     * @return The number.
     */
    @java.lang.Override
    public int getNumber() {
      return number_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (countryCode_ != 0) {
        output.writeInt32(1, countryCode_);
      }
      if (areaCode_ != 0) {
        output.writeInt32(2, areaCode_);
      }
      if (number_ != 0) {
        output.writeInt32(3, number_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (countryCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, countryCode_);
      }
      if (areaCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, areaCode_);
      }
      if (number_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, number_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cs682.samples.protos.StudentInfo.Phone)) {
        return super.equals(obj);
      }
      cs682.samples.protos.StudentInfo.Phone other = (cs682.samples.protos.StudentInfo.Phone) obj;

      if (getCountryCode()
          != other.getCountryCode()) return false;
      if (getAreaCode()
          != other.getAreaCode()) return false;
      if (getNumber()
          != other.getNumber()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COUNTRY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCountryCode();
      hash = (37 * hash) + AREA_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getAreaCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cs682.samples.protos.StudentInfo.Phone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cs682.samples.protos.StudentInfo.Phone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cs682.samples.protos.StudentInfo.Phone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cs682.samples.protos.StudentInfo.Phone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cs682.samples.protos.StudentInfo.Phone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cs682.samples.protos.StudentInfo.Phone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cs682.samples.protos.StudentInfo.Phone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cs682.samples.protos.StudentInfo.Phone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cs682.samples.protos.StudentInfo.Phone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cs682.samples.protos.StudentInfo.Phone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cs682.samples.protos.StudentInfo.Phone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cs682.samples.protos.StudentInfo.Phone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cs682.samples.protos.StudentInfo.Phone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Phone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Phone)
        cs682.samples.protos.StudentInfo.PhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cs682.samples.protos.StudentInfo.internal_static_Phone_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cs682.samples.protos.StudentInfo.internal_static_Phone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cs682.samples.protos.StudentInfo.Phone.class, cs682.samples.protos.StudentInfo.Phone.Builder.class);
      }

      // Construct using cs682.samples.protos.StudentInfo.Phone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        countryCode_ = 0;

        areaCode_ = 0;

        number_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cs682.samples.protos.StudentInfo.internal_static_Phone_descriptor;
      }

      @java.lang.Override
      public cs682.samples.protos.StudentInfo.Phone getDefaultInstanceForType() {
        return cs682.samples.protos.StudentInfo.Phone.getDefaultInstance();
      }

      @java.lang.Override
      public cs682.samples.protos.StudentInfo.Phone build() {
        cs682.samples.protos.StudentInfo.Phone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cs682.samples.protos.StudentInfo.Phone buildPartial() {
        cs682.samples.protos.StudentInfo.Phone result = new cs682.samples.protos.StudentInfo.Phone(this);
        result.countryCode_ = countryCode_;
        result.areaCode_ = areaCode_;
        result.number_ = number_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cs682.samples.protos.StudentInfo.Phone) {
          return mergeFrom((cs682.samples.protos.StudentInfo.Phone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cs682.samples.protos.StudentInfo.Phone other) {
        if (other == cs682.samples.protos.StudentInfo.Phone.getDefaultInstance()) return this;
        if (other.getCountryCode() != 0) {
          setCountryCode(other.getCountryCode());
        }
        if (other.getAreaCode() != 0) {
          setAreaCode(other.getAreaCode());
        }
        if (other.getNumber() != 0) {
          setNumber(other.getNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cs682.samples.protos.StudentInfo.Phone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cs682.samples.protos.StudentInfo.Phone) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int countryCode_ ;
      /**
       * <code>int32 country_code = 1;</code>
       * @return The countryCode.
       */
      @java.lang.Override
      public int getCountryCode() {
        return countryCode_;
      }
      /**
       * <code>int32 country_code = 1;</code>
       * @param value The countryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCode(int value) {
        
        countryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 country_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryCode() {
        
        countryCode_ = 0;
        onChanged();
        return this;
      }

      private int areaCode_ ;
      /**
       * <code>int32 area_code = 2;</code>
       * @return The areaCode.
       */
      @java.lang.Override
      public int getAreaCode() {
        return areaCode_;
      }
      /**
       * <code>int32 area_code = 2;</code>
       * @param value The areaCode to set.
       * @return This builder for chaining.
       */
      public Builder setAreaCode(int value) {
        
        areaCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 area_code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAreaCode() {
        
        areaCode_ = 0;
        onChanged();
        return this;
      }

      private int number_ ;
      /**
       * <code>int32 number = 3;</code>
       * @return The number.
       */
      @java.lang.Override
      public int getNumber() {
        return number_;
      }
      /**
       * <code>int32 number = 3;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(int value) {
        
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 number = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        
        number_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Phone)
    }

    // @@protoc_insertion_point(class_scope:Phone)
    private static final cs682.samples.protos.StudentInfo.Phone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cs682.samples.protos.StudentInfo.Phone();
    }

    public static cs682.samples.protos.StudentInfo.Phone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Phone>
        PARSER = new com.google.protobuf.AbstractParser<Phone>() {
      @java.lang.Override
      public Phone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Phone(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Phone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Phone> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cs682.samples.protos.StudentInfo.Phone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Phone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Phone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030protos/studentinfo.proto\"V\n\007Student\022\022\n" +
      "\nfirst_name\030\001 \001(\t\022\021\n\tlast_name\030\002 \001(\t\022\r\n\005" +
      "score\030\003 \003(\001\022\025\n\005phone\030\004 \001(\0132\006.Phone\"@\n\005Ph" +
      "one\022\024\n\014country_code\030\001 \001(\005\022\021\n\tarea_code\030\002" +
      " \001(\005\022\016\n\006number\030\003 \001(\005B#\n\024cs682.samples.pr" +
      "otosB\013StudentInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Score", "Phone", });
    internal_static_Phone_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Phone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Phone_descriptor,
        new java.lang.String[] { "CountryCode", "AreaCode", "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
